# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Flashcards for Pebble' do

pod 'PebbleKit', '~> 2.4'

end

target 'Flashcards for PebbleTests' do

end

